/* eslint-disable @typescript-eslint/no-explicit-any */
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateInterviewPDF(interview: any, evaluation: any) {
  const doc = new jsPDF({
    unit: "mm",
    format: "a4",
  });
  doc.setFontSize(22);
  doc.setTextColor(60, 20, 110);
  doc.text("Interview Report", 14, 20);

  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Interview Type: ${interview.interviewType}`, 14, 30);
  doc.text(`Mode: ${interview.mode}`, 14, 36);
  doc.text(`Duration: ${interview.duration}`, 14, 42);
  doc.text(`Date: ${new Date(interview.createdAt).toLocaleString()}`, 14, 48);

  doc.setFontSize(16);
  doc.setTextColor(40, 40, 40);
  doc.text("AI Evaluation Summary", 14, 62);

  autoTable(doc, {
    startY: 66,
    head: [["Metric", "Value"]],
    body: [
      ["Overall Confidence", `${evaluation.confidence}%`],
      ["Feedback", evaluation.feedback],
    ],
    headStyles: { fillColor: [110, 50, 180] },
  });

  doc.addPage("a4");

  doc.setFontSize(16);
  doc.text("Detailed Question Breakdown", 14, 20);

  const tableBody = evaluation.results.map((r: any, index: number) => [
    index + 1,
    r.question,
    r.answer || "—",
    (r.sentimentScore * 100).toFixed(0) + "%",
    r.confidence + "%",
  ]);

  autoTable(doc, {
    startY: 30,
    head: [["#", "Question", "Answer", "Sentiment", "Confidence"]],
    body: tableBody,
    styles: {
      fontSize: 10,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [110, 50, 180],
      textColor: 255,
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 70 },
      2: { cellWidth: 70 },
      3: { cellWidth: 20 },
      4: { cellWidth: 20 },
    },
  });

  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text("Generated by AI Mock Interview System", 14, 290);

  doc.save("Interview_Report.pdf");
}
